### ISSUE TITLE
Create a way to send *all* facts

### ISSUE THREAD

**Issue by dylanratcliffe** [puppetlabs/puppetlabs-splunk_hec#133]
## Use Case

Some customers rely heavily on custom facts that may be written by many different teams. When a new custom fact is created they may not want to have to change the `splunk_hec` classification to add this fact to the list of facts that are sent to Splunk (`splunk_hec::collect_facts`). Ideally customers would be able to simply send all facts to Splunk if they choose.

## Describe the Solution You Would Like

Either a flag to simply set all facts to be sent, or some more complex and flexible regex based mechanism, allowing facts that match a certain pattern to be sent.

## Describe Alternatives You've Considered

Creating some kind of logic that returns every known fact name automatically and then dynamically configures the splunk_hec module e.g.

```puppet
$all_facts = puppetdb_query('facts[name] { group by name }').map |$hash| {
  $hash['name']
}

class { 'splunk_hec':
  collect_facts => $all_facts,
}
```

Note the above code is untested, but should just work™

**Comment by dylanratcliffe** [comment]
⚠️ Turns out the code above will cause a Puppetserver restart each time the facts change. I wouldn't recommend using this.

**Comment by RandomNoun7** [comment]
@dylanratcliffe Is this a request you've gotten from a customer? This kind of thing seems possible without rebooting all the time by handling the filtering in splunk hec utils file.
If you want to see this added as a feature go ahead and create a PIE ticket in Jira and ping the team in #team-pie in Slack and we'll take a look at it. The main emphasis of our time right now isn't on this kind of feature work, so I can't promise when we would actually do it, but having it captured on our board would be a good thing.

**Comment by dylanratcliffe** [comment]
Will do

**Comment by whackyhack** [comment]
I am looking for just such an option.  One addition to consider: all-except.  If I have some facts that I really don't care in Splunk, I can ignore them but I want other facts to be sent by default.
