### ISSUE TITLE
Default collect_facts value gives issue in Puppet console

### ISSUE THREAD

**Issue by zochamx** [puppetlabs/puppetlabs-splunk_hec#41]
In the `puppetlabs-splunk_hec/manifests/init.pp`  the variable `Array $collect_facts` is initialised with the following data `['dmi','disks','partitions','processors','networking']`. 

Though when is set via **Classification -> PE Infrastructure -> Master -> Configuration** need to be valid json otherwise is converted to a string, accepted by UI but puppet agent run is failing due to the fact a string was passed. 

I would propose to change the default value to json parsable. Like `["dmi","disks","partitions","processors","networking"]`

Possibility to provide screenshots if needed.

**Comment by RandomNoun7** [comment]
Hello @zochamx,
This issue has been converted to a Jira ticket, [PIE-430](https://tickets.puppetlabs.com/browse/PIE-430).

Please view and track that ticket to keep updated on its progress. It has not yet been prioritized for work, but by watching it, you will be notified when it is.

If you have a PE support contract you can also feel free to contact your support representative reference that ticket number.

Thanks for your patience,
Bill
