### ISSUE TITLE
manage_routes => true makes pe-puppetserver.service to crash

### ISSUE THREAD

**Issue by BirgerM** [puppetlabs/puppetlabs-splunk_hec#48]
## Describe the Bug
Configuring splunk_hec as described in the documentation makes the pe-puppetserver.service to stop working.
error: `could not find terminus splunk_hec for indirection facts`

## Expected Behavior
Using the following configuration in a profile the module splunk_hec should be installed, configured and be working.

```
class { '::splunk_hec:
  url            =>$splunk_url,
  token          => $splunk_token,
  enable_reports => true,
  pe_console     => $puppet_console,
  manage_routes  => true,
}
```

## Steps to Reproduce
1. Have a roles and profiles pattern.
2. Create a profile which contains the configuration provided above
3. Add the splunk_hec module to the Puppetfile
4. Add the profile to the puppet master role
5. Run puppet on the puppet master

## Environment
 - Version: Puppet Enterprise 2019.2.2
 - Platform: RHEL 7

## Additional Context
Using this module out of the box will not create a working facts terminus. Trying to restart pe-puppetserver.service will make it fail because it does not recognize the cache: splunk_hec option in splunk_hec_route.yaml.

**Comment by BirgerM** [comment]
This problem was caused by local hardening settings on the Puppet Master and has nothing to do with the splunk_hec module.

**Comment by fetzerms** [comment]
@BirgerM Hey! We are currently facing the same issue. Can you maybe give us a pointer on what was going wrong?

**Comment by coreymbe** [comment]
@fetzerms :: That error in particular, as well as the cause is addressed in the README under Custom Installation. https://github.com/puppetlabs/puppetlabs-splunk_hec/#Custom-Installation
